spring.application.name=skins

# 1. Endereço do Banco (A "estrada" para o banco)
spring.datasource.url=jdbc:postgresql://localhost:5432/skinsdb

# 2. Credenciais (A "chave" de entrada)
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Driver (O "tradutor" que o Java usa para falar com o Postgres)
spring.datasource.driver-class-name=org.postgresql.Driver